### ISSUE TITLE
Not working anymore?

### ISSUE THREAD

**Issue by CrappyUser** [javiersantos/GoodbyeBackspaceChrome#3]
Using Chrome 40 (on Win7 Home Premium x64) can't seem to have the extension actually work at all,
[this other extension](https://chrome.google.com/webstore/detail/pidcjgldchekcoolelhbjfbnccjkckfj) that did the same also stopped working :v good job Google

**Comment by javiersantos** [comment]
Hi @CrappyUser.
It seems GoodbyeBackspace continues working properly, at least using Linux. Could someone else confirm it?
